################################
# Direct dependencies

[[constraint]]
  name = "github.com/coreos/bbolt"
  source = "https://github.com/coreos/bbolt"
  version = "=v1.3.1-coreos.6"

[[constraint]]
  name = "github.com/google/btree"
  source = "https://github.com/google/btree"
  revision = "925471ac9e2131377a91e1595defec898166fe49"

[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go"
  version = "=v1.7.5"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  source = "https://github.com/grpc-ecosystem/grpc-gateway"
  version = "=v1.3.1"

[[constraint]]
  name = "github.com/tmc/grpc-websocket-proxy"
  source = "https://github.com/tmc/grpc-websocket-proxy"
  revision = "89b8d40f7ca833297db804fcb3be53a76d01c238"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  source = "https://github.com/grpc-ecosystem/go-grpc-prometheus"
  revision = "0dafe0d496ea71181bf2dd039e7e3f44b6bd11a7"

[[constraint]]
  name = "github.com/gogo/protobuf"
  source = "https://github.com/gogo/protobuf"
  version = "=v0.5"

[[constraint]]
  name = "github.com/golang/protobuf"
  source = "https://github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"

[[constraint]]
  name = "github.com/soheilhy/cmux"
  source = "https://github.com/soheilhy/cmux"
  version = "=v0.1.3"

[[constraint]]
  name = "github.com/golang/groupcache"
  source = "https://github.com/golang/groupcache"
  revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"

[[constraint]]
  name = "golang.org/x/time"
  source = "https://github.com/golang/time"
  revision = "c06e80d9300e4443158a03817b8a8cb37d230320"

[[constraint]]
  name = "golang.org/x/net"
  source = "https://github.com/golang/net"
  revision = "66aacef3dd8a676686c7ae3716979581e8b03c47"

[[constraint]]
  name = "golang.org/x/crypto"
  source = "https://github.com/golang/crypto"
  revision = "9419663f5a44be8b34ca85f08abc5fe1be11f8a3"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  source = "https://github.com/coreos/go-systemd"
  version = "=v15"

[[constraint]]
  name = "github.com/coreos/go-semver"
  source = "https://github.com/coreos/go-semver"
  version = "=v0.2.0"

[[constraint]]
  name = "github.com/coreos/pkg"
  source = "https://github.com/coreos/pkg"
  version = "=v3"

[[constraint]]
  name = "github.com/spf13/cobra"
  source = "https://github.com/spf13/cobra"
  revision = "1c44ec8d3f1552cac48999f9306da23c4d8a288b"

[[constraint]]
  name = "github.com/spf13/pflag"
  source = "https://github.com/spf13/pflag"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  source = "https://github.com/urfave/cli"
  version = "=v1.18.0"

[[constraint]]
  name = "github.com/ugorji/go"
  source = "https://github.com/ugorji/go"
  revision = "bdcc60b419d136a85cdf2e7cbcac34b3f1cd6e57"

[[constraint]]
  name = "github.com/kr/pty"
  source = "https://github.com/kr/pty"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  source = "https://github.com/bgentry/speakeasy"
  version = "=v0.1.0"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  source = "https://github.com/dustin/go-humanize"
  revision = "bb3d318650d48840a39aa21a027c6630e198e626"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  source = "https://github.com/olekukonko/tablewriter"
  revision = "a0225b3f23b5ce0cbec6d7a66a968f8a59eca9c4"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  source = "https://github.com/cheggaaa/pb"
  version = "=v1.0.2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  source = "https://github.com/ghodss/yaml"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/jonboulle/clockwork"
  source = "https://github.com/jonboulle/clockwork"
  version = "=v0.1.0"

[[constraint]]
  name = "github.com/xiang90/probing"
  source = "https://github.com/xiang90/probing"
  version = "=0.0.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  source = "https://github.com/dgrijalva/jwt-go"
  version = "=v3.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  source = "https://github.com/prometheus/client_golang"
  revision = "5cec1d0429b02e4323e042eb04dafdb079ddf568"

[[constraint]]
  name = "github.com/prometheus/client_model"
  source = "https://github.com/prometheus/client_model"
  revision = "6f3806018612930941127f2a7c6c453ba2c527d2"

################################

################################
# Transitive dependencies, and overrides

[[override]]
  name = "google.golang.org/genproto"
  source = "https://github.com/google/go-genproto"
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"

[[override]]
  name = "golang.org/x/sys"
  source = "https://github.com/golang/sys"
  revision = "ebfc5b4631820b793c9010c87fd8fef0f39eb082"

[[override]]
  name = "golang.org/x/text"
  source = "https://github.com/golang/text"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"

[[override]]
  name = "github.com/gorilla/websocket"
  source = "https://github.com/gorilla/websocket"
  revision = "4201258b820c74ac8e6922fc9e6b52f71fe46f8d"

[[override]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/go-yaml/yaml"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"

[[override]]
  name = "github.com/cpuguy83/go-md2man"
  source = "https://github.com/cpuguy83/go-md2man"
  revision = "23709d0847197db6021a51fdb193e66e9222d4e7"

[[override]]
  name = "github.com/russross/blackfriday"
  source = "https://github.com/russross/blackfriday"
  revision = "4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c"

[[override]]
  name = "github.com/prometheus/common"
  source = "https://github.com/prometheus/common"
  revision = "e3fb1a1acd7605367a2b378bc2e2f893c05174b7"

[[override]]
  name = "github.com/prometheus/procfs"
  source = "https://github.com/prometheus/procfs"
  revision = "a6e9df898b1336106c743392c48ee0b71f5c4efa"

[[override]]
  name = "github.com/beorn7/perks"
  source = "https://github.com/beorn7/perks"
  revision = "4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9"

[[override]]
  name = "github.com/sirupsen/logrus"
  source = "https://github.com/sirupsen/logrus"
  version = "=v1.0.3"

[[override]]
  name = "github.com/mattn/go-runewidth"
  source = "https://github.com/mattn/go-runewidth"
  version = "=v0.0.2"

################################
