name: Coverage
on: [push]
permissions: read-all
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-amd64-coverage
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
        go-version: "1.19.4"
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        mkdir "${TARGET}"
        case "${TARGET}" in
          linux-amd64-coverage)
            GOARCH=amd64 ./scripts/codecov_upload.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
