name: functional-arm64-tests
on:
  schedule:
    - cron: '0 0/4 * * *' # runs every 4 hours
permissions: read-all
jobs:
  test:
    runs-on: [Linux, ARM64]
    strategy:
      fail-fast: true
      matrix:
        target:
          - linux-arm64-functional
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          ref: main
          go-version: "1.19.5"
      - run: date
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          echo "${TARGET}"
          case "${TARGET}" in
            linux-arm64-functional)
              GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh && GOARCH=arm64 PASSES='functional' ./scripts/test.sh
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
