name: Linearizability Nightly
on:
  # schedules always run against the main branch
  schedule:
    - cron: '25 9 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    # GHA has a maximum amount of 6h execution time, we try to get done within 3h
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
    - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
        go-version: "1.19.4"
    - run: |
        make gofail-enable
        make build
        mkdir -p /tmp/linearizability
        cat server/etcdserver/raft.fail.go
        EXPECT_DEBUG=true GO_TEST_FLAGS='-v --count 500 --failfast --run TestLinearizability --timeout=170m' RESULTS_DIR=/tmp/linearizability make test-linearizability
    - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
      if: always()
      with:
        path: /tmp/linearizability/*
