name: Linearizability Nightly
on:
  # schedules always run against the main branch, hence we have to create separate jobs
  # with individual checkout actions for each of the active release branches
  schedule:
    - cron: '25 9 * * *' # runs every day at 09:25 UTC
jobs:
  test-main:
    # GHA has a maximum amount of 6h execution time, we try to get done within 3h
    uses: ./.github/workflows/linearizability-template.yaml
    with:
      ref: main
      count: 100
      testTimeout: 200m
  test-35:
    uses: ./.github/workflows/linearizability-template.yaml
    with:
      ref: release-3.5
      count: 100
      testTimeout: 200m
  test-34:
    uses: ./.github/workflows/linearizability-template.yaml
    with:
      ref: release-3.4
      count: 100
      testTimeout: 200m
